---
name: nsreroot
on: push
jobs:
  build:
    strategy:
        matrix:
          compiler: [ g++, clang++ ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./
        with:
          directory: nsreroot
          dependencies_debian: libx11-dev xterm
          environment: "{CXX:${{ matrix.env }}}"
  envtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./
        with:
          directory: nsreroot
          environment: "{ 'CXX': 'clang++' }"
  presets:
    strategy:
        matrix:
          preset: 
            - clang-tidy
            - iwyu
            - cppcheck
            - clang-sanitize-address
            - clang-sanitize-memory
            - clang-sanitize-undefined
            - clang-sanitize-dataflow
            - clang-sanitize-safe-stack
            - valgrind
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./
        with:
          directory: nsreroot
          preset: ${{ matrix.preset }}
